/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug/': RouteRecordInfo<
      '/debug/',
      '/debug',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug/b': RouteRecordInfo<
      '/debug/b',
      '/debug/b',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug/controls': RouteRecordInfo<
      '/debug/controls',
      '/debug/controls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug/font': RouteRecordInfo<
      '/debug/font',
      '/debug/font',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug/script-launcher': RouteRecordInfo<
      '/debug/script-launcher',
      '/debug/script-launcher',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug/test': RouteRecordInfo<
      '/debug/test',
      '/debug/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/debug/test2': RouteRecordInfo<
      '/debug/test2',
      '/debug/test2',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/library/': RouteRecordInfo<
      '/library/',
      '/library',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/library/commands': RouteRecordInfo<
      '/library/commands',
      '/library/commands',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/library/guides': RouteRecordInfo<
      '/library/guides',
      '/library/guides',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/library/maps/[id]': RouteRecordInfo<
      '/library/maps/[id]',
      '/library/maps/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/library/maps/maps': RouteRecordInfo<
      '/library/maps/maps',
      '/library/maps/maps',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/library/units': RouteRecordInfo<
      '/library/units',
      '/library/units',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/news/': RouteRecordInfo<
      '/news/',
      '/news',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/news/overview': RouteRecordInfo<
      '/news/overview',
      '/news/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/play/': RouteRecordInfo<
      '/play/',
      '/play',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/play/campaign': RouteRecordInfo<
      '/play/campaign',
      '/play/campaign',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/play/customLobbies': RouteRecordInfo<
      '/play/customLobbies',
      '/play/customLobbies',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/play/lobby': RouteRecordInfo<
      '/play/lobby',
      '/play/lobby',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/play/matchmaking': RouteRecordInfo<
      '/play/matchmaking',
      '/play/matchmaking',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/play/menu': RouteRecordInfo<
      '/play/menu',
      '/play/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/play/scenarios': RouteRecordInfo<
      '/play/scenarios',
      '/play/scenarios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/play/skirmishVsAi': RouteRecordInfo<
      '/play/skirmishVsAi',
      '/play/skirmishVsAi',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/play/tournaments': RouteRecordInfo<
      '/play/tournaments',
      '/play/tournaments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/profile/[userId]': RouteRecordInfo<
      '/profile/[userId]',
      '/profile/:userId',
      { userId: ParamValue<true> },
      { userId: ParamValue<false> },
      | never
    >,
    '/watch/': RouteRecordInfo<
      '/watch/',
      '/watch',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/watch/replays': RouteRecordInfo<
      '/watch/replays',
      '/watch/replays',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/renderer/views/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/renderer/views/debug/index.vue': {
      routes:
        | '/debug/'
      views:
        | never
    }
    'src/renderer/views/debug/b.vue': {
      routes:
        | '/debug/b'
      views:
        | never
    }
    'src/renderer/views/debug/controls.vue': {
      routes:
        | '/debug/controls'
      views:
        | never
    }
    'src/renderer/views/debug/font.vue': {
      routes:
        | '/debug/font'
      views:
        | never
    }
    'src/renderer/views/debug/script-launcher.vue': {
      routes:
        | '/debug/script-launcher'
      views:
        | never
    }
    'src/renderer/views/debug/test.vue': {
      routes:
        | '/debug/test'
      views:
        | never
    }
    'src/renderer/views/debug/test2.vue': {
      routes:
        | '/debug/test2'
      views:
        | never
    }
    'src/renderer/views/library/index.vue': {
      routes:
        | '/library/'
      views:
        | never
    }
    'src/renderer/views/library/commands.vue': {
      routes:
        | '/library/commands'
      views:
        | never
    }
    'src/renderer/views/library/guides.vue': {
      routes:
        | '/library/guides'
      views:
        | never
    }
    'src/renderer/views/library/maps/[id].vue': {
      routes:
        | '/library/maps/[id]'
      views:
        | never
    }
    'src/renderer/views/library/maps/maps.vue': {
      routes:
        | '/library/maps/maps'
      views:
        | never
    }
    'src/renderer/views/library/units.vue': {
      routes:
        | '/library/units'
      views:
        | never
    }
    'src/renderer/views/news/index.vue': {
      routes:
        | '/news/'
      views:
        | never
    }
    'src/renderer/views/news/overview.vue': {
      routes:
        | '/news/overview'
      views:
        | never
    }
    'src/renderer/views/play/index.vue': {
      routes:
        | '/play/'
      views:
        | never
    }
    'src/renderer/views/play/campaign.vue': {
      routes:
        | '/play/campaign'
      views:
        | never
    }
    'src/renderer/views/play/customLobbies.vue': {
      routes:
        | '/play/customLobbies'
      views:
        | never
    }
    'src/renderer/views/play/lobby.vue': {
      routes:
        | '/play/lobby'
      views:
        | never
    }
    'src/renderer/views/play/matchmaking.vue': {
      routes:
        | '/play/matchmaking'
      views:
        | never
    }
    'src/renderer/views/play/menu.vue': {
      routes:
        | '/play/menu'
      views:
        | never
    }
    'src/renderer/views/play/scenarios.vue': {
      routes:
        | '/play/scenarios'
      views:
        | never
    }
    'src/renderer/views/play/skirmishVsAi.vue': {
      routes:
        | '/play/skirmishVsAi'
      views:
        | never
    }
    'src/renderer/views/play/tournaments.vue': {
      routes:
        | '/play/tournaments'
      views:
        | never
    }
    'src/renderer/views/profile/[userId].vue': {
      routes:
        | '/profile/[userId]'
      views:
        | never
    }
    'src/renderer/views/watch/index.vue': {
      routes:
        | '/watch/'
      views:
        | never
    }
    'src/renderer/views/watch/replays.vue': {
      routes:
        | '/watch/replays'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
